name: run-test
run-name: Run main tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./install && ./vendor/bin/sail up -d
      - run: ./vendor/bin/sail test --do-not-cache-result
